language: python
sudo: false
os:
  - linux

python:
  - "3.5"

env:
  - TOX_ENV=py35-dj19
  - TOX_ENV=py34-dj19
  - TOX_ENV=py27-dj19
  - TOX_ENV=py35-dj18
  - TOX_ENV=py34-dj18
  - TOX_ENV=py27-dj18

matrix:
    fast_finish: true

install:
    - pip install tox

script:
    - tox -e $TOX_ENV

notifications:
  webhooks:
    urls:
      - http://staging.rmotr.com/api/v1/webhooks/travis/build-project
    on_success: always
    on_failure: always
    on_start: never
